<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fql</string>
	</array>
	<key>name</key>
	<string>FQL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(?i:\b(select|get(\s\(header\))?(\s\(txt\))?(\s\(html\))?|header|use|from|search|limit))</string>
			<key>name</key>
			<string>keyword.other.fql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.fql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fql</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.fql</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parentheses</string>
			<key>match</key>
			<string>(\()(.*?)(\))</string>
			<key>name</key>
			<string>string.other.fql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.fql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fql</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.fql</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double quotes</string>
			<key>match</key>
			<string>(")(.*?)(")</string>
			<key>name</key>
			<string>string.quotes.double.fql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.fql</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>(\d+)</string>
			<key>name</key>
			<string>constant.numeric.fql</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fql</string>
	<key>uuid</key>
	<string>5b8e4cd0-5bb3-4b48-b23d-85ad17fde4f9</string>
</dict>
</plist>
