<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fql</string>
	</array>
	<key>name</key>
	<string>FQL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#parentheses</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#double_quotes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--.*$</string>
					<key>name</key>
					<string>comment.line.double-dash.fql</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\/\*</string>
					<key>end</key>
					<string>\*\/</string>
					<key>name</key>
					<string>comment.block.fql</string>
				</dict>
			</array>
		</dict>
		<key>double_quotes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.fql</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.fql</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.fql</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(")(.*?)(")</string>
					<key>name</key>
					<string>string.quotes.double.fql</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i:\b(select|get|post|delete|header|use|from|search|limit))</string>
					<key>name</key>
					<string>keyword.other.fql</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.fql</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+)</string>
					<key>name</key>
					<string>constant.numeric.fql</string>
				</dict>
			</array>
		</dict>
		<key>parentheses</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.fql</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.fql</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.fql</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\()(.*?)(\))</string>
					<key>name</key>
					<string>string.other.fql</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fql</string>
	<key>uuid</key>
	<string>5b8e4cd0-5bb3-4b48-b23d-85ad17fde4f9</string>
</dict>
</plist>
